"""
Exercise catalog for the therapist program builder.

Each entry uses the V1 canonical schema. video_url is a placeholder (empty
string) until YouTube embed URLs are confirmed for each exercise. v2_ghost_supported
is True only for exercises with a verified V2 ghost coach in strength_app —
v2_exercise_key is the matching key in strength_app.exercise_system.exercise_registry_v2
EXERCISE_METADATA, which routes to the live ghost+voice template.
"""

EXERCISES = [
    # ------------------------------------------------------------------
    # SQUAT
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_bw_squat",
        "name": "Bodyweight Squat",
        "movement_pattern": "Squat",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "full_squats",
        "description": "Full-depth squat with bodyweight only. Trains knee tracking, hip mobility, and glute activation.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_goblet_squat",
        "name": "Goblet Squat",
        "movement_pattern": "Squat",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "goblet_squat",
        "description": "Squat holding a dumbbell at chest height. Counterbalance promotes depth while reinforcing bracing.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 75,
    },
    {
        "exercise_id": "ex_wall_sit",
        "name": "Wall Sit",
        "movement_pattern": "Squat",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "wall_sit_rx",
        "description": "Isometric quad hold at 90° knee flexion against a wall. Builds endurance without axial loading.",
        "default_sets": 3,
        "default_reps": 30,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_split_squat",
        "name": "Split Squat",
        "movement_pattern": "Squat",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "bulgarian_split_squats",
        "description": "Stationary split-stance squat. Addresses single-leg strength asymmetry with a controlled descent.",
        "default_sets": 3,
        "default_reps": 8,
        "default_rest_seconds": 75,
    },
    # ------------------------------------------------------------------
    # HINGE
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_rdl",
        "name": "Romanian Deadlift",
        "movement_pattern": "Hinge",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "bodyweight_rdl",
        "description": "Hip hinge lowering dumbbells along the legs to mid-shin. Loads hamstrings and glutes eccentrically.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 90,
    },
    {
        "exercise_id": "ex_glute_bridge",
        "name": "Glute Bridge",
        "movement_pattern": "Hinge",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "glute_bridge",
        "description": "Supine hip thrust driving glutes into full extension. Ideal for early-stage glute activation.",
        "default_sets": 3,
        "default_reps": 15,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_single_leg_rdl",
        "name": "Single-Leg RDL",
        "movement_pattern": "Hinge",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "single_leg_rdl",
        "description": "Stand on one leg. Hinge forward at the hip while the other leg extends behind. Reach toward the floor with hands. Return to standing.",
        "default_sets": 3,
        "default_reps": 8,
        "default_rest_seconds": 90,
    },
    {
        "exercise_id": "ex_clamshell",
        "name": "Banded Clamshell",
        "movement_pattern": "Hinge",
        "equipment": "Band",
        "video_url": "https://www.youtube.com/embed/v8MoNZBxw1A",
        "v2_ghost_supported": True,
        "v2_exercise_key": "clamshells",
        "description": "Lie on your side with knees bent at 90°, feet stacked together, resistance band above knees. Keep feet touching and lift your top knee toward the ceiling. Pause, then slowly lower.",
        "default_sets": 3,
        "default_reps": 15,
        "default_rest_seconds": 45,
    },
    # ------------------------------------------------------------------
    # PUSH
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_wall_pushup",
        "name": "Wall Push-up",
        "movement_pattern": "Push",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "wall_push_up",
        "description": "Vertical push against a wall. Entry-level pressing pattern for shoulder and wrist re-conditioning.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_incline_pushup",
        "name": "Incline Push-up",
        "movement_pattern": "Push",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "push_ups",
        "description": "Push-up with hands elevated on a bench. Scales load while building shoulder stability.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_db_shoulder_press",
        "name": "Dumbbell Shoulder Press",
        "movement_pattern": "Push",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "db_shoulder_press_rx",
        "description": "Seated overhead dumbbell press. Develops deltoid and rotator cuff strength through a full range.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 75,
    },
    # ------------------------------------------------------------------
    # PULL
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_band_row",
        "name": "Resistance Band Row",
        "movement_pattern": "Pull",
        "equipment": "Band",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Seated or standing horizontal row with a band. Builds mid-back strength and scapular retraction.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_db_bent_row",
        "name": "Dumbbell Bent-over Row",
        "movement_pattern": "Pull",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "dumbbell_rowing",
        "description": "Hip-hinged unilateral dumbbell row. Loads the lats and rhomboids through a full pulling range.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 75,
    },
    {
        "exercise_id": "ex_band_pull_apart",
        "name": "Band Pull-apart",
        "movement_pattern": "Pull",
        "equipment": "Band",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "band_pull_apart",
        "description": "Horizontal band pull with arms extended at shoulder height. Activates rear delts and improves posture.",
        "default_sets": 3,
        "default_reps": 15,
        "default_rest_seconds": 45,
    },
    # ------------------------------------------------------------------
    # LUNGE
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_forward_lunge",
        "name": "Forward Lunge",
        "movement_pattern": "Lunge",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "lunges",
        "description": "Alternating forward step into a deep lunge. Trains single-leg strength and dynamic balance.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_lateral_lunge",
        "name": "Lateral Lunge",
        "movement_pattern": "Lunge",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "lateral_lunges",
        "description": "Side step into a single-leg squat. Targets adductors and abductors in the frontal plane.",
        "default_sets": 3,
        "default_reps": 8,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_step_up",
        "name": "Step-up",
        "movement_pattern": "Lunge",
        "equipment": "Step",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "step_ups",
        "description": "Unilateral step onto a box or stair. Emphasises eccentric quad control and single-leg hip drive.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 75,
    },
    # ------------------------------------------------------------------
    # CORE
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_sl_balance",
        "name": "Single-Leg Balance",
        "movement_pattern": "Core",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "single_leg_balance_rx",
        "description": "Eyes-open static stance on one leg. Trains ankle and knee proprioception in closed kinetic chain.",
        "default_sets": 3,
        "default_reps": 30,
        "default_rest_seconds": 45,
    },
    {
        "exercise_id": "ex_dead_bug",
        "name": "Dead Bug",
        "movement_pattern": "Core",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "dead_bug",
        "description": "Supine alternating arm-leg extension. Trains anti-extension core stability with lumbar neutral.",
        "default_sets": 3,
        "default_reps": 8,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_side_plank",
        "name": "Side Plank",
        "movement_pattern": "Core",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "side_plank_rx",
        "description": "Lateral isometric hold from elbow and feet. Loads the lateral chain and quadratus lumborum.",
        "default_sets": 3,
        "default_reps": 20,
        "default_rest_seconds": 60,
    },
    # ------------------------------------------------------------------
    # PLYOMETRICS
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_plyo_tuck_jumps",
        "name": "Tuck Jumps",
        "movement_pattern": "Plyometrics",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "tuck_jumps",
        "description": "Explosive vertical jump pulling the knees up toward the chest mid-air. Builds power and absorbs impact through soft, bent-knee landings.",
        "default_sets": 3,
        "default_reps": 5,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_plyo_broad_jump",
        "name": "Broad Jump",
        "movement_pattern": "Plyometrics",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "broad_jump",
        "description": "Standing long jump for horizontal distance with a stuck landing. Trains triple-extension power and deceleration control.",
        "default_sets": 3,
        "default_reps": 5,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_plyo_lateral_bound_stick",
        "name": "Lateral Bound and Stick",
        "movement_pattern": "Plyometrics",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        # B1 (health sweep): was 'lateral_bound_stick' — a curated json stub
        # with EMPTY phases and no registry object; this key has full CV
        # phase targets + registry parity (same PLYO_LATERAL_BOUND_STICK
        # js_type, so the JS landing coach is unchanged).
        "v2_exercise_key": "lateral_bound_and_stick",
        "description": "Side-to-side bound onto a single leg with a three-second stuck landing. Trains lateral power and frontal-plane knee control.",
        "default_sets": 3,
        "default_reps": 5,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_plyo_sl_hop_lateral",
        "name": "Single-Leg Hop Lateral",
        "movement_pattern": "Plyometrics",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "single_leg_hop_lateral",
        "description": "Same-leg lateral hops with a stuck landing each rep. Loads the ankle and glute medius in the frontal plane.",
        "default_sets": 3,
        "default_reps": 5,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_plyo_sl_hop_forward",
        "name": "Single-Leg Hop Forward",
        "movement_pattern": "Plyometrics",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "single_leg_hop_forward",
        "description": "Continuous forward hops on a single leg with soft landings. Trains horizontal single-leg power and shock absorption.",
        "default_sets": 3,
        "default_reps": 5,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_plyo_sl_landing",
        "name": "Single-Leg Landing",
        "movement_pattern": "Plyometrics",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "single_leg_landing",
        "description": "Two-foot takeoff landing on one leg, held for three seconds. ACL injury-prevention drill — trains single-leg deceleration without knee valgus.",
        "default_sets": 3,
        "default_reps": 5,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_ankle_pumps",
        "name": "Ankle Pumps",
        "movement_pattern": "Mobility",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Lying or sitting with the leg straight, slowly point the toes away (downward), then pull them back up toward the shin, moving through the full pain-free range. Keep it slow and controlled — the knee stays still and only the ankle moves. Promotes circulation and ankle mobility.",
        "default_sets": 3,
        "default_reps": 15,
        "default_rest_seconds": 30,
    },
    {
        "exercise_id": "ex_slr",
        "name": "Straight Leg Raise",
        "movement_pattern": "Activation",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "straight_leg_raise_rx",
        "description": "Lie on your back, working leg straight, other knee bent with the foot flat. Tighten the thigh to lock the knee fully straight, then lift the straight leg to about the height of the bent knee. Hold briefly and lower slowly with control. Keep the knee dead straight throughout — the lift comes from the hip, not a bending knee.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 45,
    },
    {
        "exercise_id": "ex_supine_hip_abduction",
        "name": "Supine Hip Abduction",
        "movement_pattern": "Activation",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "supine_hip_abduction_rx",
        "description": "Lie on your back with both legs straight. Keeping the knee straight and toes pointing to the ceiling, slide the working leg out to the side along the floor as far as is comfortable, then bring it slowly back to the middle. Keep the pelvis level and the toes facing up — don't let the leg roll outward.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 45,
    },
    {
        "exercise_id": "ex_knee_to_chest",
        "name": "Knee to Chest",
        "movement_pattern": "Mobility",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "knee_to_chest_rx",
        "description": "Lie on your back. Bring one knee up toward your chest and gently clasp behind the thigh, drawing the knee in until you feel a comfortable stretch in the hip and lower back. Keep the other leg relaxed. Hold for about 20 seconds, breathe, then lower slowly. Move gently — never force the range. (Each rep = one ~20s hold.)",
        "default_sets": 3,
        "default_reps": 20,
        "default_rest_seconds": 30,
    },
    {
        "exercise_id": "ex_sidelying_hip_abduction",
        "name": "Side-lying Hip Abduction",
        "movement_pattern": "Activation",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "sidelying_hip_abduction_rx",
        "description": "Lie on your side, bottom leg bent for support, top leg straight and in line with your body. Keeping the top leg straight and toes pointing forward (not up), lift it toward the ceiling to about 45°, then lower slowly. Keep the hips stacked and don't roll backward — it's a pure sideways lift driven by the outer hip.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 45,
    },
    {
        "exercise_id": "ex_prone_glute_squeeze",
        "name": "Prone Glute Squeeze",
        "movement_pattern": "Activation",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Lie face down with legs straight and relaxed. Squeeze your buttocks together firmly without lifting the legs or arching the back, hold for about 5 seconds, then fully relax. Keep breathing through the hold. The movement is the squeeze itself, not leg lifting. (Each rep = one ~5s squeeze.)",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 30,
    },
    {
        "exercise_id": "ex_prone_knee_bend",
        "name": "Prone Knee Bend",
        "movement_pattern": "Mobility",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "prone_knee_bend_rx",
        "description": "Lie face down with both legs straight. Slowly bend the working knee, bringing the heel toward your buttock as far as is comfortable, then lower it back down with control. Keep the hips flat and the thigh still — only the knee moves. Restores knee-bending range; stop at a gentle stretch, not pain.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 45,
    },
    {
        "exercise_id": "ex_plank_hold",
        "name": "Plank Hold",
        "movement_pattern": "Core",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,  # DARK — flip after filming protocol
        "v2_exercise_key": "plank_hold_rx",
        "description": "Support yourself on your forearms and toes, elbows under the shoulders. Hold a straight line from head to heels — squeeze the glutes and brace the abdominals so the hips neither sag nor pike up. Breathe steadily and hold. End the hold when you can no longer keep the straight line. (Each rep = one ~30s hold.)",
        "default_sets": 3,
        "default_reps": 30,
        "default_rest_seconds": 60,
    },
]

EXERCISES_BY_ID = {e["exercise_id"]: e for e in EXERCISES}
PATTERNS = ["Squat", "Hinge", "Push", "Pull", "Lunge", "Core", "Plyometrics", "Mobility", "Activation"]
