"""
Exercise catalog for the therapist program builder.

Each entry uses the V1 canonical schema. video_url is a placeholder (empty
string) until YouTube embed URLs are confirmed for each exercise. v2_ghost_supported
is True only for exercises with a verified V2 ghost coach in strength_app —
v2_exercise_key is the matching key in strength_app.exercise_system.exercise_registry_v2
EXERCISE_METADATA, which routes to the live ghost+voice template.
"""

EXERCISES = [
    # ------------------------------------------------------------------
    # SQUAT
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_bw_squat",
        "name": "Bodyweight Squat",
        "movement_pattern": "Squat",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "full_squats",
        "description": "Full-depth squat with bodyweight only. Trains knee tracking, hip mobility, and glute activation.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_goblet_squat",
        "name": "Goblet Squat",
        "movement_pattern": "Squat",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Squat holding a dumbbell at chest height. Counterbalance promotes depth while reinforcing bracing.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 75,
    },
    {
        "exercise_id": "ex_wall_sit",
        "name": "Wall Sit",
        "movement_pattern": "Squat",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Isometric quad hold at 90° knee flexion against a wall. Builds endurance without axial loading.",
        "default_sets": 3,
        "default_reps": 30,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_split_squat",
        "name": "Split Squat",
        "movement_pattern": "Squat",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "bulgarian_split_squats",
        "description": "Stationary split-stance squat. Addresses single-leg strength asymmetry with a controlled descent.",
        "default_sets": 3,
        "default_reps": 8,
        "default_rest_seconds": 75,
    },
    # ------------------------------------------------------------------
    # HINGE
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_rdl",
        "name": "Romanian Deadlift",
        "movement_pattern": "Hinge",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "deadlift_dumbbell",
        "description": "Hip hinge lowering dumbbells along the legs to mid-shin. Loads hamstrings and glutes eccentrically.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 90,
    },
    {
        "exercise_id": "ex_glute_bridge",
        "name": "Glute Bridge",
        "movement_pattern": "Hinge",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "glute_bridge",
        "description": "Supine hip thrust driving glutes into full extension. Ideal for early-stage glute activation.",
        "default_sets": 3,
        "default_reps": 15,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_single_leg_rdl",
        "name": "Single-Leg RDL",
        "movement_pattern": "Hinge",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Unilateral Romanian deadlift on one leg. Challenges hip stability and proprioception on the stance side.",
        "default_sets": 3,
        "default_reps": 8,
        "default_rest_seconds": 90,
    },
    {
        "exercise_id": "ex_clamshell",
        "name": "Banded Clamshell",
        "movement_pattern": "Hinge",
        "equipment": "Band",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "clamshells",
        "description": "Side-lying hip abduction with a resistance band. Isolates glute medius for lateral hip stability.",
        "default_sets": 3,
        "default_reps": 15,
        "default_rest_seconds": 45,
    },
    # ------------------------------------------------------------------
    # PUSH
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_wall_pushup",
        "name": "Wall Push-up",
        "movement_pattern": "Push",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Vertical push against a wall. Entry-level pressing pattern for shoulder and wrist re-conditioning.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_incline_pushup",
        "name": "Incline Push-up",
        "movement_pattern": "Push",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "push_ups",
        "description": "Push-up with hands elevated on a bench. Scales load while building shoulder stability.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_db_shoulder_press",
        "name": "Dumbbell Shoulder Press",
        "movement_pattern": "Push",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Seated overhead dumbbell press. Develops deltoid and rotator cuff strength through a full range.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 75,
    },
    # ------------------------------------------------------------------
    # PULL
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_band_row",
        "name": "Resistance Band Row",
        "movement_pattern": "Pull",
        "equipment": "Band",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Seated or standing horizontal row with a band. Builds mid-back strength and scapular retraction.",
        "default_sets": 3,
        "default_reps": 12,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_db_bent_row",
        "name": "Dumbbell Bent-over Row",
        "movement_pattern": "Pull",
        "equipment": "Dumbbell",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "dumbbell_rowing",
        "description": "Hip-hinged unilateral dumbbell row. Loads the lats and rhomboids through a full pulling range.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 75,
    },
    {
        "exercise_id": "ex_band_pull_apart",
        "name": "Band Pull-apart",
        "movement_pattern": "Pull",
        "equipment": "Band",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Horizontal band pull with arms extended at shoulder height. Activates rear delts and improves posture.",
        "default_sets": 3,
        "default_reps": 15,
        "default_rest_seconds": 45,
    },
    # ------------------------------------------------------------------
    # LUNGE
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_forward_lunge",
        "name": "Forward Lunge",
        "movement_pattern": "Lunge",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "lunges",
        "description": "Alternating forward step into a deep lunge. Trains single-leg strength and dynamic balance.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_lateral_lunge",
        "name": "Lateral Lunge",
        "movement_pattern": "Lunge",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "lateral_lunges",
        "description": "Side step into a single-leg squat. Targets adductors and abductors in the frontal plane.",
        "default_sets": 3,
        "default_reps": 8,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_step_up",
        "name": "Step-up",
        "movement_pattern": "Lunge",
        "equipment": "Step",
        "video_url": "",
        "v2_ghost_supported": True,
        "v2_exercise_key": "step_ups",
        "description": "Unilateral step onto a box or stair. Emphasises eccentric quad control and single-leg hip drive.",
        "default_sets": 3,
        "default_reps": 10,
        "default_rest_seconds": 75,
    },
    # ------------------------------------------------------------------
    # CORE
    # ------------------------------------------------------------------
    {
        "exercise_id": "ex_sl_balance",
        "name": "Single-Leg Balance",
        "movement_pattern": "Core",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Eyes-open static stance on one leg. Trains ankle and knee proprioception in closed kinetic chain.",
        "default_sets": 3,
        "default_reps": 30,
        "default_rest_seconds": 45,
    },
    {
        "exercise_id": "ex_dead_bug",
        "name": "Dead Bug",
        "movement_pattern": "Core",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Supine alternating arm-leg extension. Trains anti-extension core stability with lumbar neutral.",
        "default_sets": 3,
        "default_reps": 8,
        "default_rest_seconds": 60,
    },
    {
        "exercise_id": "ex_side_plank",
        "name": "Side Plank",
        "movement_pattern": "Core",
        "equipment": "None",
        "video_url": "",
        "v2_ghost_supported": False,
        "v2_exercise_key": "",
        "description": "Lateral isometric hold from elbow and feet. Loads the lateral chain and quadratus lumborum.",
        "default_sets": 3,
        "default_reps": 20,
        "default_rest_seconds": 60,
    },
]

EXERCISES_BY_ID = {e["exercise_id"]: e for e in EXERCISES}
PATTERNS = ["Squat", "Hinge", "Push", "Pull", "Lunge", "Core"]
