# Generated by Django 4.2 on 2026-03-21 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hindi', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('grain', 'Grains & Rice'), ('dal', 'Dal & Legumes'), ('vegetable', 'Vegetables'), ('fruit', 'Fruits'), ('dairy', 'Dairy'), ('non_veg', 'Non-Vegetarian'), ('snack', 'Snacks & Street Food'), ('beverage', 'Beverages'), ('oil_fat', 'Oils & Fats'), ('sweet', 'Sweets & Desserts'), ('mess', 'Mess / Canteen Common')], max_length=20)),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField(default=0)),
                ('carbs_per_100g', models.FloatField(default=0)),
                ('fat_per_100g', models.FloatField(default=0)),
                ('fiber_per_100g', models.FloatField(default=0)),
                ('serving_size_g', models.FloatField(default=100)),
                ('serving_description', models.CharField(blank=True, help_text="e.g. '1 medium bowl', '2 rotis'", max_length=80)),
                ('is_mess_common', models.BooleanField(default=False, help_text='Commonly served in hostel mess')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrition_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('athletic_performance', 'Athletic Performance'), ('rehabilitation', 'Rehabilitation / Recovery')], default='maintenance', max_length=30)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (desk job, little exercise)'), ('lightly_active', 'Lightly Active (1–3 days/week)'), ('moderately_active', 'Moderately Active (3–5 days/week)'), ('very_active', 'Very Active (6–7 days/week)'), ('extra_active', 'Extra Active (athlete / physical job)')], default='moderately_active', max_length=20)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('biological_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('target_calories', models.IntegerField(default=0)),
                ('target_protein_g', models.IntegerField(default=0)),
                ('target_carbs_g', models.IntegerField(default=0)),
                ('target_fat_g', models.IntegerField(default=0)),
                ('mess_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to='strength_app.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], default='lunch', max_length=15)),
                ('raw_description', models.TextField(blank=True)),
                ('guidance_text', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('food_items_served', models.ManyToManyField(blank=True, related_name='mess_appearances', to='strength_app.fooditem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_entries', to='strength_app.patientprofile')),
            ],
            options={
                'ordering': ['-entry_date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='DailyFoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('quantity_g', models.FloatField(default=100, help_text='Grams consumed')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], default='lunch', max_length=15)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('calories_logged', models.FloatField(default=0)),
                ('protein_logged', models.FloatField(default=0)),
                ('carbs_logged', models.FloatField(default=0)),
                ('fat_logged', models.FloatField(default=0)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='strength_app.fooditem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='strength_app.patientprofile')),
            ],
            options={
                'ordering': ['log_date', 'meal_type', 'logged_at'],
            },
        ),
    ]
