# Generated by Django 4.2 on 2026-03-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0002_fooditem_nutritionprofile_messentry_dailyfoodlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfoodlog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], default='lunch', max_length=15),
        ),
        migrations.AlterField(
            model_name='sessionfeedback',
            name='pain_reported',
            field=models.CharField(choices=[('none', 'None'), ('mild', 'Mild Discomfort'), ('moderate', 'Moderate Pain'), ('severe', 'Severe Pain')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='therapistprescription',
            name='prescription_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
