# Generated by Django 4.2 on 2026-03-26 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0003_alter_dailyfoodlog_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
