# Generated by Django 4.2 on 2026-03-30 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0004_alter_patientprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='athlete_sport',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='athlete_tier_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='athlete_tier_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FootballProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hop_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('nordic_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('sprint_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('pogo_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('cod_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ybalance_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('hop_left_cm', models.FloatField(blank=True, null=True)),
                ('hop_right_cm', models.FloatField(blank=True, null=True)),
                ('nordic_seconds', models.FloatField(blank=True, null=True)),
                ('sprint_seconds', models.FloatField(blank=True, null=True)),
                ('pogo_clean_reps', models.IntegerField(blank=True, null=True)),
                ('cod_left_seconds', models.FloatField(blank=True, null=True)),
                ('cod_right_seconds', models.FloatField(blank=True, null=True)),
                ('ybalance_left_pct', models.FloatField(blank=True, null=True)),
                ('ybalance_right_pct', models.FloatField(blank=True, null=True)),
                ('football_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fv_tendency', models.CharField(choices=[('force_dominant', 'Force-Dominant'), ('velocity_dominant', 'Velocity-Dominant'), ('balanced', 'Balanced')], default='balanced', max_length=20)),
                ('lsi_flag', models.BooleanField(default=False)),
                ('hop_lsi_pct', models.FloatField(blank=True, null=True)),
                ('cod_lsi_pct', models.FloatField(blank=True, null=True)),
                ('ybalance_lsi_pct', models.FloatField(blank=True, null=True)),
                ('hsr_current_phase', models.CharField(choices=[('hsr_phase_1', 'HSR Phase 1'), ('hsr_phase_2', 'HSR Phase 2'), ('hsr_phase_3', 'HSR Phase 3')], default='hsr_phase_1', max_length=20)),
                ('plyometric_cleared', models.CharField(choices=[('none', 'Not Cleared'), ('low_load', 'Low-Load'), ('moderate_load', 'Moderate-Load'), ('high_load', 'High-Load')], default='none', max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='football_profile', to='strength_app.patientprofile')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
