# Generated by Django 4.2 on 2026-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0005_patientprofile_athlete_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballprofile',
            name='hsr_weeks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballprofile',
            name='last_reassessment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
