# Generated by Django 4.2 on 2026-04-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0006_footballprofile_hsr_weeks_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='raw_test_data_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
