# Generated by Django 4.2 on 2026-04-03 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0007_patientprofile_raw_test_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballprofile',
            name='season_phase',
            field=models.CharField(choices=[('off_season', 'Off-Season'), ('pre_season', 'Pre-Season'), ('in_season', 'In-Season'), ('post_season', 'Post-Season')], default='in_season', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='session_rpe',
            field=models.IntegerField(default=5, help_text='Session RPE 1-10: How hard was this session overall?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='MatchDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('opponent', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_dates', to='strength_app.patientprofile')),
            ],
            options={
                'ordering': ['match_date'],
                'unique_together': {('patient', 'match_date')},
            },
        ),
    ]
