# Generated by Django 4.2 on 2026-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0008_football_season_match_rpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
    ]
