# Generated by Django 4.2 on 2026-05-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0009_add_xp_earned_to_workout_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='therapist_managed',
            field=models.BooleanField(default=False),
        ),
    ]
