# Generated by Django 4.2 on 2026-06-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0010_patientprofile_therapist_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballprofile',
            name='hsr_phase_start_week',
            field=models.IntegerField(default=0),
        ),
    ]
