# Generated by Django 4.2 on 2026-06-11 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0011_footballprofile_hsr_phase_start_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionfeedback',
            name='session_rpe',
            field=models.IntegerField(default=5, help_text='Session RPE 1-10 — used for load and recovery trends', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
