# Generated by Django 4.2 on 2026-06-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0013_redflagevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseexecution',
            name='rep_quality_source',
            field=models.CharField(choices=[('cv', 'CV-classified per rep'), ('derived', 'Estimated from form score')], default='derived', max_length=10),
        ),
    ]
