# Generated by Django 4.2 on 2026-06-11 18:10
#
# DA-P4: hsr_phase_start_week becomes nullable. The old default=0 was
# indistinguishable from "phase legitimately started at week 0", and the
# falsy re-anchor check froze weeks_in_phase at 0 forever. Existing rows
# with 0 were unanchored sentinels — convert them to NULL so the next
# session anchors them correctly.

from django.db import migrations, models


def zero_to_null(apps, schema_editor):
    FootballProfile = apps.get_model('strength_app', 'FootballProfile')
    FootballProfile.objects.filter(hsr_phase_start_week=0).update(
        hsr_phase_start_week=None
    )


def null_to_zero(apps, schema_editor):
    FootballProfile = apps.get_model('strength_app', 'FootballProfile')
    FootballProfile.objects.filter(hsr_phase_start_week__isnull=True).update(
        hsr_phase_start_week=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0014_exerciseexecution_rep_quality_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballprofile',
            name='hsr_phase_start_week',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(zero_to_null, null_to_zero),
    ]
