# Generated by Django 4.2 on 2026-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0016_age_validator_18_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseexecution',
            name='category',
            field=models.CharField(choices=[('lower_body', 'Lower Body'), ('posterior_chain', 'Posterior Chain'), ('upper_body', 'Upper Body'), ('cardio', 'Cardio'), ('stretching', 'Stretching'), ('core', 'Core'), ('power', 'Power / Plyometric'), ('balance', 'Balance')], max_length=20),
        ),
    ]
