# Generated by Django 4.2.30 on 2026-07-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_app', '0006_sessionlogitem_started_at_exercisesetlog'),
        ('strength_app', '0022_restevent_painevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='restevent',
            name='session_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_events', to='therapist_app.sessionlog'),
        ),
        migrations.AddField(
            model_name='restevent',
            name='set_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restevent',
            name='context',
            field=models.CharField(choices=[('between_sets', 'Between sets'), ('between_exercises', 'Between exercises'), ('pause', 'Session paused')], default='between_sets', max_length=20),
        ),
        migrations.AlterField(
            model_name='restevent',
            name='extra_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
