# Generated by Django 4.2.30 on 2026-07-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0023_restevent_session_log_restevent_set_number_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='painevent',
            index=models.Index(fields=['patient', 'created_at'], name='strength_ap_patient_6a440b_idx'),
        ),
    ]
