# Generated by Django 4.2 on 2026-05-07 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes_for_patient', models.TextField(blank=True, default='')),
                ('draft_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-week_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, default='', max_length=200)),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('clinic_name', models.CharField(blank=True, default='', max_length=200)),
                ('seat_limit', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TherapistPatientLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('archived', 'Archived')], default='pending', max_length=10)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, default='', max_length=12)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('primary_condition', models.CharField(blank=True, default='', max_length=200)),
                ('condition_tone', models.CharField(choices=[('primary', 'Primary'), ('warn', 'Warn'), ('error', 'Error'), ('neutral', 'Neutral'), ('green', 'Green')], default='primary', max_length=10)),
                ('injury_date', models.DateField(blank=True, null=True)),
                ('program_start', models.DateField(blank=True, null=True)),
                ('total_weeks', models.IntegerField(default=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_links', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='therapist_app.therapist')),
            ],
            options={
                'ordering': ['-invited_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapistMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='therapist_app.therapistpatientlink')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('flagged', 'Flagged')], default='draft', max_length=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='therapist_reports/')),
                ('generated_by', models.CharField(choices=[('auto', 'Auto'), ('therapist', 'Manual')], default='therapist', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='therapist_app.therapistpatientlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('exercise_id', models.CharField(max_length=100)),
                ('exercise_name', models.CharField(max_length=200)),
                ('movement_pattern', models.CharField(blank=True, default='', max_length=60)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=10)),
                ('load', models.CharField(blank=True, default='BW', max_length=80)),
                ('rest_seconds', models.IntegerField(default=60)),
                ('tempo', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='therapist_app.prescription')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='therapist_app.therapistpatientlink'),
        ),
        migrations.AddConstraint(
            model_name='therapistpatientlink',
            constraint=models.UniqueConstraint(fields=('therapist', 'patient'), name='unique_therapist_patient'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('link', 'week_number'), name='unique_link_week'),
        ),
    ]
