# Generated by Django 4.2 on 2026-05-07 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_pain', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('overall_comment', models.TextField(blank=True, default='')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='therapist_app.therapistpatientlink')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='therapist_app.prescription')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapistPatientHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('affected_side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('bilateral', 'Bilateral'), ('na', 'N/A')], default='', max_length=10)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('pain_medications', models.TextField(blank=True, default='')),
                ('other_conditions', models.TextField(blank=True, default='')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('goals', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='therapist_app.therapistpatientlink')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('exercise_id', models.CharField(blank=True, default='', max_length=100)),
                ('exercise_name', models.CharField(blank=True, default='', max_length=200)),
                ('sets_completed', models.IntegerField(default=0)),
                ('pain', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('right', 'Just right'), ('hard', 'Hard'), ('too_hard', 'Too hard')], default='', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_items', to='therapist_app.prescriptionitem')),
                ('session_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='therapist_app.sessionlog')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
