# Generated by Django 4.2 on 2026-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_app', '0002_sessionlog_therapistpatienthealthprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistpatientlink',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
