# Generated by Django 4.2.30 on 2026-07-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_app', '0005_prescriptionitem_pain_stop_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlogitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExerciseSetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(blank=True, default='', max_length=100)),
                ('exercise_name', models.CharField(blank=True, default='', max_length=200)),
                ('set_number', models.PositiveSmallIntegerField(default=1)),
                ('mode', models.CharField(choices=[('camera', 'Camera-tracked'), ('guided', 'Guided (self-reported)')], default='guided', max_length=10)),
                ('reps_count', models.PositiveSmallIntegerField(default=0)),
                ('hold_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps_json', models.JSONField(blank=True, default=list)),
                ('demo_viewed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='therapist_app.therapistpatientlink')),
                ('session_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='therapist_app.sessionlog')),
            ],
            options={
                'ordering': ['session_log_id', 'exercise_id', 'set_number', 'id'],
                'indexes': [models.Index(fields=['session_log', 'exercise_id'], name='therapist_a_session_58068f_idx')],
            },
        ),
    ]
