# Generated by Django 4.2.30 on 2026-07-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength_app', '0023_restevent_session_log_restevent_set_number_and_more'),
        ('therapist_app', '0007_sessionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_logs', to='therapist_app.prescription'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_reports', to='therapist_app.therapistpatientlink'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_reports', to='strength_app.patientprofile'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='session_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='therapist_app.sessionlog'),
        ),
    ]
