# Generated by Django 4.2.30 on 2026-07-10 16:04
# B-D1 (2026-07 exam): dedupe first — update_or_create without a DB
# constraint was get-then-insert, so concurrent retries could have written
# duplicate (session_log, exercise_id, set_number) rows. Keep the NEWEST row
# of each group (it carries the latest reps_json), delete the rest, then add
# the constraint that makes recurrence impossible.

from django.db import migrations, models


def dedupe_set_logs(apps, schema_editor):
    ExerciseSetLog = apps.get_model('therapist_app', 'ExerciseSetLog')
    seen = {}
    for row in ExerciseSetLog.objects.order_by('-id').iterator():
        key = (row.session_log_id, row.exercise_id, row.set_number)
        if key in seen:
            row.delete()
        else:
            seen[key] = row.id


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_app', '0008_alter_sessionlog_prescription_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_set_logs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='exercisesetlog',
            constraint=models.UniqueConstraint(fields=('session_log', 'exercise_id', 'set_number'), name='uniq_setlog_session_exercise_set'),
        ),
    ]
